# filepath: .github/workflows/build-extension.yml
name: Build Extension with Secrets

on:
  workflow_dispatch: # Allows manual triggering
  push:
    tags:
      - 'v*.*.*' # Or trigger on new tags for releases
      - 'v*.*.*-*' # Also trigger on pre-release tags like v1.0.0-alpha.1

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write # Needed to create releases
    steps:
      - name: Checkout code
        uses: actions/checkout@v4 # Updated to v4

      - name: Bump manifest.json version from tag
        if: startsWith(github.ref, 'refs/tags/')
        run: |
          VERSION=${GITHUB_REF#refs/tags/v}
          echo "🔖 Setting manifest.json version → $VERSION"
          sed -i "s/\"version\": \"[^\"]*\"/\"version\": \"$VERSION\"/" manifest.json

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Install dependencies
        run: npm ci

      - name: Build extension
        run: npm run build

      - name: Replace placeholders
        run: |
          sed -i "s|'%%NCBI_TOOL_NAME%%'|'${{ secrets.NCBI_TOOL_NAME_SECRET }}'|g" ./content/ncbi_api_handler.js
          sed -i "s|'%%NCBI_API_EMAIL%%'|'${{ secrets.NCBI_API_EMAIL_SECRET }}'|g" ./content/ncbi_api_handler.js

      - name: Create ZIP Package
        run: |
          zip -r mdpi-filter.zip . \
            -x "node_modules/*" \
            -x ".git/*" \
            -x ".github/*" \
            -x "package.json" \
            -x "package-lock.json" \
            -x "README.md" \
            -x "SECURITY.md" \
            -x "PRIVACY_POLICY.md" \
            -x "docs/PRIVACY_POLICY.md" \
            -x "docs/index.html" \
            -x "*.zip"

      - name: Upload Extension Artifact
        uses: actions/upload-artifact@v4
        with:
          name: extension
          path: mdpi-filter.zip

      - name: Create Release
        if: startsWith(github.ref, 'refs/tags/')
        uses: softprops/action-gh-release@v2
        with:
          files: mdpi-filter.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}